name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: windows-2022

    steps:
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d_%H%M%S')" >> $env:GITHUB_OUTPUT
    - uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Restore Packages
      run: nuget restore NekoForWindows.sln

    - name: Build Solution
      run: msbuild.exe NekoForWindows.sln /p:Configuration=Release /p:PostBuildEventUseInBuild=false

    - name: Upload Release
      uses: actions/upload-artifact@v3
      with:
        path: |
          NekoForWindows/bin/Release/NekoForWindows.exe
        name: NekoForWindows_release_${{ github.head_ref || github.ref_name }}_${{ steps.date.outputs.date }}