name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-debug:
    name: Build Debug
    runs-on: windows-2022

    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d_%H%M%S')" >> $env:GITHUB_OUTPUT

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1.3

      - name: Build Debug
        run: |
          msbuild NekoForWindows.sln /p:Configuration=Debug /p:PostBuildEventUseInBuild=false

      - name: Upload Debug
        uses: actions/upload-artifact@v3
        with:
          path: |
           NekoForWindows/bin/Debug/NekoForWindows.exe
          name: NekoForWindows_debug_${{ github.head_ref || github.ref_name }}_${{ steps.date.outputs.date }}

  build-release:
    name: Build Release
    runs-on: windows-2022

    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d_%H%M%S')" >> $env:GITHUB_OUTPUT

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1.3

      - name: Build Release
        run: |
          msbuild NekoForWindows.sln /p:Configuration=Release /p:PostBuildEventUseInBuild=false

      - name: Upload Release
        uses: actions/upload-artifact@v3
        with:
          path: |
           NekoForWindows/bin/Release/NekoForWindows.exe
          name: NekoForWindows_release_${{ github.head_ref || github.ref_name }}_${{ steps.date.outputs.date }}